# This workflow uses actions that are not certified by GitHub.
# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: ci-nest-10

on:
  # Triggers the workflow on push or pull request events but only for selected branch
  push:
    branches:
      - main
      # - nest-10
#
env:
  REGISTRY_USER: ${{ vars.REGISTRY_USER }}
  FRAMEWORK_NAME: ${{ vars.FRAMEWORK_NAME }}
  FRAMEWORK_VERSION: ${{ vars.FRAMEWORK_VERSION }}
  DIR_NODE_NAME: ${{ vars.DIR_NODE_NAME }}
  DIR_TEMPLATES: ${{ vars.DIR_TEMPLATES }}
#
jobs:
  # This workflow contains jobs called "docker"
  build:
    name: Docker build and push
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY_USER }}/${{ env.FRAMEWORK_NAME }}${{ env.FRAMEWORK_VERSION }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=vin,priority=100,enable=${{ github.ref == format('refs/heads/{0}', 'nest-10') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/nest-10')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        if: github.event_name == 'push' && (github.ref == 'refs/heads/nest-10')
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_TEMPLATES }}/${{ env.FRAMEWORK_NAME }}-${{ env.FRAMEWORK_VERSION }}/${{ env.DIR_NODE_NAME }}/
          file: ${{ env.DIR_TEMPLATES }}/${{ env.FRAMEWORK_NAME }}-${{ env.FRAMEWORK_VERSION }}/${{ env.DIR_NODE_NAME }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
